### ISSUE TITLE
Add constructor which wraps an existing Skija Canvas

### ISSUE THREAD

**Issue by mipastgt** [jfree/skijagraphics2d#1]
It would be nice to add a constructor which wraps an existing Skija `Canvas` without first explicitly creating a `Surface`. With such a constructor this code could be used in conjunction with Jetbrains Compose. Compose can provide you with a `NativeCanvas` object which is just a type alias for `org.jetbrains.skija.Canvas` and if you could wrap that you could use all your AWT rendering stuff in the context of Jetbrains Compose. This also needs some changes or disabling of the `create` method.

**Comment by jfree** [comment]
I made some changes that I think achieve the goal, but I don't use Jetbrains Compose (yet) so I can't be 100% sure.

**Comment by mipastgt** [comment]
Looks good to me so far. I'll give it a try as soon as I can.

**Comment by jfree** [comment]
Great, thanks!

**Comment by mipastgt** [comment]
Nothing special but the proof that it works. See attachments: main.kt, snapshot
[main.kt.zip](https://github.com/jfree/skijagraphics2d/files/6836678/main.kt.zip)
<img width="924" alt="shapshot" src="https://user-images.githubusercontent.com/16735714/126076740-45df7a48-0c64-4abb-b0d9-ec2a028c8236.png">

**Comment by jfree** [comment]
Very nice...it feels like opening a new door and looking through!

**Comment by jfree** [comment]
By the way, I'm wondering how to publish SkijaGraphics2D to the Maven Central Repository.  Right now I've got a platform specific dependency for Skija (skija-macos-x64).  I've never had to deal with such things before...can I just add scope = 'provided'?  Or some other approach?

**Comment by mipastgt** [comment]
You can use a classifier which you can provided via a profile. If you create profiles for Windows, Mac, Linux in your Maven file, you can cover all cases. I don't know whether there is a better solution. If in doubt the scope = provided approach should also work (sort of) but is better than a hard (but maybe wrong) dependency.

**Comment by jfree** [comment]
I used that, thanks.
